services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp_development
      POSTGRES_USER: user
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
  rails:
    build:
      context: ./rails
    command: bash -c "touch log/development.log && tail -f log/development.log"
    environment:
      - RAILS_ENV=development
    volumes:
      - ./rails:/myapp
    ports:
      - 3000:3000
    depends_on:
      - db
    tty: true
    stdin_open: true
  react:
    build:
      context: ./react
    tty: true
    stdin_open: true
    volumes:
      - ./react:/myapp
    ports:
      - 4000:4000
volumes:
  postgres_data:
