default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  host: db
  <<: *default
  database: myapp_development
  username: user
  password: password

test:
  <<: *default
  host: db
  database: myapp_test

production:
  <<: *default
  host: db
  database: myapp_production
  username: myapp
  password: <%= ENV["MYAPP_DATABASE_PASSWORD"] %>
